#!/bin/sh
chmod +x  /etc/init.d/znetcontrol /usr/bin/znetcontrol*
uci -q batch <<-EOF >/dev/null
    delete ucitrack.@znetcontrol[-1]
    add ucitrack znetcontrol
    set ucitrack.@znetcontrol[-1].init=znetcontrol
    commit ucitrack
EOF

[ -s /etc/config/znetcontrol ] ||  echo "config global 'settings'" > /etc/config/znetcontrol
rm -f /tmp/luci-indexcache
exit 0
