#!/bin/sh /etc/rc.common
#
# ZNetControl init.d脚本

START=99
USE_PROCD=1

NAME=znetcontrol
LOCK="/var/lock/$NAME.lock"

start_instance() {
     procd_open_instance
     procd_set_param command /usr/bin/znetcontrolctrl
     procd_set_param respawn
     procd_set_param stderr 1
     procd_close_instance
}

_timecontrol_start() {
     if [ "$(grep -c "option enable .1." /etc/config/$NAME 2>/dev/null)" -gt "0" ]; then
        touch $LOCK
        znetcontrol start
        start_instance
     else
            echo "INFO: 没有启用规则！"
        stop_service
     fi
}

start_service(){
    [ -f $LOCK ] && exit
    _timecontrol_start
    rm -f $LOCK
}

service_triggers() {
     procd_add_reload_trigger 'znetcontrol'
}

stop_service(){
    kill -9 $(ps -w | grep 'znetcontrolctrl' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
    rm -f $LOCK 2>/dev/null
    znetcontrol stop
}
